INC = -I ../include
OBJ = -o ../build

all: exercise2_1 exercise2_2 #exercise1_3 exercise1_4 exercise1_5 exercise1_6

exercise2_1: exercise2_1.cpp
	g++ $(INC) $(OBJ)/exercise2_1 exercise2_1.cpp

exercise2_2: exercise2_2.cpp
	g++ $(INC) $(OBJ)/exercise2_2 exercise2_2.cpp

# exercise1_3: exercise1_3.cpp
# 	g++ $(INC) $(OBJ)/exercise1_3 exercise1_3.cpp

# exercise1_4: exercise1_4.cpp
# 	g++ $(INC) $(OBJ)/exercise1_4 exercise1_4.cpp

# exercise1_5: exercise1_5.cpp
# 	g++ $(INC) $(OBJ)/exercise1_5 exercise1_5.cpp

# exercise1_6: exercise1_6.cpp
# 	g++ $(INC) $(OBJ)/exercise1_6 exercise1_6.cpp

# .PHONY: clean

# clean:
#     $(RM) *.o *~ $(MAIN)