all: exercise1_1 exercise1_2 exercise1_3 exercise1_4 exercise1_5 exercise1_6 exercise2_1 exercise2_2 exercise2_3 exercise2_4 exercise2_5 exercise2_6

exercise1_1: exercise1_1.cpp
	g++ exercise1_1 exercise1_1.cpp

exercise1_2: exercise1_2.cpp
	g++ exercise1_2 exercise1_2.cpp

exercise1_3: exercise1_3.cpp
	g++ exercise1_3 exercise1_3.cpp

exercise1_4: exercise1_4.cpp
	g++ exercise1_4 exercise1_4.cpp

exercise1_5: exercise1_5.cpp
	g++ exercise1_5 exercise1_5.cpp

exercise1_6: exercise1_6.cpp
	g++ exercise1_6 exercise1_6.cpp

exercise2_1: exercise2_1.cpp
	g++ exercise2_1 exercise2_1.cpp

exercise2_2: exercise2_2.cpp
	g++ exercise2_2 exercise2_2.cpp

exercise2_3: exercise2_3.cpp
	g++ exercise2_3 exercise2_3.cpp

exercise2_4: exercise2_4.cpp
	g++ exercise2_4 exercise2_4.cpp

exercise2_5: exercise2_5.cpp
	g++ exercise2_5 exercise2_5.cpp

exercise2_6: exercise2_6.cpp
	g++ exercise2_6 exercise2_6.cpp